import os
import shutil
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from main import run_retrieval_flow, run_ingestion_pipeline
from processing.storage import supabase

print("--- API Server Initializing ---")

app = FastAPI()

# Enable CORS for React dev server
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

@app.get("/")
def read_root():
    return {"status": "online", "message": "SLM RAG API is running"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}

class QueryRequest(BaseModel):
    query: str
    mode: str

class QueryHistoryRequest(BaseModel):
    query: str
    mode: str
    history: list[dict] = []

@app.post("/query")
def query_system(request: QueryRequest):
    # Backward compatibility
    from retrieval import mode_router
    result = mode_router.handle_query(supabase, request.query, request.mode)
    return {"result": result}

@app.post("/chat")
def chat_system(request: QueryHistoryRequest):
    """
    Handles conversational RAG with history.
    """
    from retrieval import mode_router
    result = mode_router.handle_query(supabase, request.query, request.mode, request.history)
    return {"result": result}

@app.post("/upload-document")
async def upload_document_full(
    file: UploadFile = File(...),
    document_title: str = os.getenv("DEFAULT_TITLE", "Untitled"),
    uploaded_by: str = os.getenv("DEFAULT_USER", "Anonymous"),
    timestamp: str = None
):
    """
    Enhanced upload endpoint: 
    1. Saves locally
    2. Uploads to SharePoint
    3. Stores metadata in DB
    4. Triggers ingestion
    """
    suffix = os.path.splitext(file.filename)[1]
    if suffix.lower() not in ['.pdf', '.docx', '.md']:
        raise HTTPException(status_code=400, detail="Unsupported file format")

    try:
        # 1. Save local temporary copy for processing
        file_path = os.path.join(UPLOAD_DIR, file.filename)
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        # 2. SharePoint Upload
        from processing.sharepoint import SharePointService
        sp_service = SharePointService()
        sp_result = sp_service.upload_file(file_path)
        
        sharepoint_url = sp_result.get("sharepoint_url")
        sharepoint_file_id = sp_result.get("sharepoint_file_id")

        # 3. Trigger Ingestion with full metadata
        # document_id will be generated by validator.validate_document inside run_ingestion_pipeline
        # We pass metadata down to be stored in the documents table
        run_ingestion_pipeline(
            file_path, 
            title=document_title,
            sharepoint_url=sharepoint_url,
            sharepoint_file_id=sharepoint_file_id,
            uploaded_by=uploaded_by
        )

        # 4. Fetch the generated document_id (UUID) to return to UI
        # We retrieve it from the documents table using the filename and SharePoint info
        doc_res = supabase.table("documents").select("id").eq("sharepoint_file_id", sharepoint_file_id).execute()
        document_id = doc_res.data[0]["id"] if doc_res.data else "unknown"

        return {
            "status": "success",
            "document_id": document_id,
            "sharepoint_url": sharepoint_url
        }

    except Exception as e:
        print(f"Upload flow failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/upload")
async def upload_document_legacy(file: UploadFile = File(...)):
    """
    Legacy upload endpoint (backward compatibility).
    """
    # ... existing implementation or redirect to full
    return await upload_document_full(file)

@app.get("/documents")
async def list_documents():
    """
    Retrieves unique document IDs from the sections table.
    """
    try:
        # Simple retrieval from sections table
        response = supabase.table("sections").select("document_id").execute()
        
        # Get unique IDs
        doc_ids = list(set([item['document_id'] for item in response.data]))
        
        # Map to a more friendly format
        documents = [{"id": doc_id, "name": f"Document {doc_id[:8]}..."} for doc_id in doc_ids]
        
        return {"documents": documents}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
